--
-- PostgreSQL database dump
--

-- Dumped from database version 10.16
-- Dumped by pg_dump version 10.16

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: plpgsql; Type: EXTENSION; Schema: -; Owner:
--

CREATE EXTENSION IF NOT EXISTS plpgsql WITH SCHEMA pg_catalog;


--
-- Name: EXTENSION plpgsql; Type: COMMENT; Schema: -; Owner:
--

COMMENT ON EXTENSION plpgsql IS 'PL/pgSQL procedural language';


--
-- Name: pgcrypto; Type: EXTENSION; Schema: -; Owner:
--

CREATE EXTENSION IF NOT EXISTS pgcrypto WITH SCHEMA public;


--
-- Name: EXTENSION pgcrypto; Type: COMMENT; Schema: -; Owner:
--

COMMENT ON EXTENSION pgcrypto IS 'cryptographic functions';


SET default_tablespace = '';

SET default_with_oids = false;

--
-- Name: addresses; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.addresses (
                                  id bigint NOT NULL,
                                  house_number character varying(255),
                                  city_id bigint NOT NULL,
                                  street character varying(255)
);


ALTER TABLE public.addresses OWNER TO postgres;

--
-- Name: addresses_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.addresses ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.addresses_id_seq
START WITH 1
          INCREMENT BY 1
          NO MINVALUE
          NO MAXVALUE
          CACHE 1
          );


--
-- Name: cities; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.cities (
                               id bigint NOT NULL,
                               name character varying(255),
                               zipcode character varying(255)
);


ALTER TABLE public.cities OWNER TO postgres;

--
-- Name: cities_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.cities ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.cities_id_seq
START WITH 1
          INCREMENT BY 1
          NO MINVALUE
          NO MAXVALUE
          CACHE 1
          );


--
-- Name: delivered_baggage; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.delivered_baggage (
                                          id bigint NOT NULL,
                                          type integer NOT NULL,
                                          volume double precision NOT NULL,
                                          weight double precision NOT NULL,
                                          description character varying(255)
);


ALTER TABLE public.delivered_baggage OWNER TO postgres;

--
-- Name: delivered_baggage_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.delivered_baggage ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.delivered_baggage_id_seq
START WITH 1
          INCREMENT BY 1
          NO MINVALUE
          NO MAXVALUE
          CACHE 1
          );


--
-- Name: delivery_applications; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.delivery_applications (
                                              id bigint NOT NULL,
                                              receiving_date date NOT NULL,
                                              sending_date date NOT NULL,
                                              baggage_id bigint NOT NULL,
                                              receiver_address_id bigint NOT NULL,
                                              sender_address_id bigint NOT NULL,
                                              user_id bigint NOT NULL,
                                              state integer NOT NULL,
                                              price double precision NOT NULL
);


ALTER TABLE public.delivery_applications OWNER TO postgres;

--
-- Name: delivery_applications_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.delivery_applications ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.delivery_applications_id_seq
START WITH 1
          INCREMENT BY 1
          NO MINVALUE
          NO MAXVALUE
          CACHE 1
          );


--
-- Name: delivery_receipts; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.delivery_receipts (
                                          id bigint NOT NULL,
                                          formation_date date,
                                          paid boolean,
                                          total_price double precision,
                                          application_id bigint,
                                          manager_user_id bigint,
                                          customer_user_id bigint
);


ALTER TABLE public.delivery_receipts OWNER TO postgres;

--
-- Name: delivery_receipts_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.delivery_receipts ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.delivery_receipts_id_seq
START WITH 1
          INCREMENT BY 1
          NO MINVALUE
          NO MAXVALUE
          CACHE 1
          );


--
-- Name: dimensions_fares; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.dimensions_fares (
                                         id bigint NOT NULL,
                                         dimensions_from integer,
                                         dimensions_to integer,
                                         price double precision
);


ALTER TABLE public.dimensions_fares OWNER TO postgres;

--
-- Name: dimensions_fares_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.dimensions_fares ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.dimensions_fares_id_seq
START WITH 1
          INCREMENT BY 1
          NO MINVALUE
          NO MAXVALUE
          CACHE 1
          );


--
-- Name: directions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.directions (
                                   id bigint NOT NULL,
                                   distance double precision,
                                   receiver_city_id bigint,
                                   sender_city_id bigint
);


ALTER TABLE public.directions OWNER TO postgres;

--
-- Name: directions_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.directions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.directions_id_seq
START WITH 1
          INCREMENT BY 1
          NO MINVALUE
          NO MAXVALUE
          CACHE 1
          );


--
-- Name: distance_fares; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.distance_fares (
                                       id bigint NOT NULL,
                                       distance_from integer,
                                       distance_to integer,
                                       price double precision
);


ALTER TABLE public.distance_fares OWNER TO postgres;

--
-- Name: distance_fares_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.distance_fares ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.distance_fares_id_seq
START WITH 1
          INCREMENT BY 1
          NO MINVALUE
          NO MAXVALUE
          CACHE 1
          );


--
-- Name: user_role; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.user_role (
                                  user_id bigint NOT NULL,
                                  roles character varying(255)
);


ALTER TABLE public.user_role OWNER TO postgres;

--
-- Name: users; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.users (
                              id bigint NOT NULL,
                              cash numeric(19,2),
                              email character varying(255),
                              name character varying(32) NOT NULL,
                              phone character varying(13),
                              surname character varying(32) NOT NULL,
                              login character varying(16) NOT NULL,
                              address_id bigint,
                              password character varying(256)
);


ALTER TABLE public.users OWNER TO postgres;

--
-- Name: users_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_id_seq
START WITH 1
          INCREMENT BY 1
          NO MINVALUE
          NO MAXVALUE
          CACHE 1
          );


--
-- Name: weight_fares; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.weight_fares (
                                     id bigint NOT NULL,
                                     price double precision,
                                     weight_from integer,
                                     weight_to integer
);


ALTER TABLE public.weight_fares OWNER TO postgres;

--
-- Name: weight_fares_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.weight_fares ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.weight_fares_id_seq
START WITH 1
          INCREMENT BY 1
          NO MINVALUE
          NO MAXVALUE
          CACHE 1
          );


--
-- Name: addresses addresses_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.addresses
    ADD CONSTRAINT addresses_pkey PRIMARY KEY (id);


--
-- Name: cities cities_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.cities
    ADD CONSTRAINT cities_pkey PRIMARY KEY (id);


--
-- Name: delivered_baggage delivered_baggage_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.delivered_baggage
    ADD CONSTRAINT delivered_baggage_pkey PRIMARY KEY (id);


--
-- Name: delivery_applications delivery_applications_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.delivery_applications
    ADD CONSTRAINT delivery_applications_pkey PRIMARY KEY (id);


--
-- Name: delivery_receipts delivery_receipts_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.delivery_receipts
    ADD CONSTRAINT delivery_receipts_pkey PRIMARY KEY (id);


--
-- Name: dimensions_fares dimensions_fares_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.dimensions_fares
    ADD CONSTRAINT dimensions_fares_pkey PRIMARY KEY (id);


--
-- Name: directions directions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.directions
    ADD CONSTRAINT directions_pkey PRIMARY KEY (id);


--
-- Name: distance_fares distance_fares_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.distance_fares
    ADD CONSTRAINT distance_fares_pkey PRIMARY KEY (id);


--
-- Name: cities id_zip_code_constraint; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.cities
    ADD CONSTRAINT id_zip_code_constraint UNIQUE (id, zipcode);


--
-- Name: addresses unique_address; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.addresses
    ADD CONSTRAINT unique_address UNIQUE (house_number, city_id, street);

--
-- Name: directions unique_constraint; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.directions
    ADD CONSTRAINT unique_constraint UNIQUE (distance, receiver_city_id, sender_city_id);


--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- Name: weight_fares weight_fares_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.weight_fares
    ADD CONSTRAINT weight_fares_pkey PRIMARY KEY (id);


--
-- Name: delivery_applications delivery_applications_users_fk; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.delivery_applications
    ADD CONSTRAINT delivery_applications_users_fk FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: directions direction_sender_city_fk; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.directions
    ADD CONSTRAINT direction_sender_city_fk FOREIGN KEY (sender_city_id) REFERENCES public.cities(id);


--
-- Name: delivery_receipts receipts_applications_fk; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.delivery_receipts
    ADD CONSTRAINT receipts_applications_fk FOREIGN KEY (application_id) REFERENCES public.delivery_applications(id);


--
-- Name: addresses address_city_fk; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.addresses
    ADD CONSTRAINT address_city_fk FOREIGN KEY (city_id) REFERENCES public.cities(id);


--
-- Name: delivery_receipts receipts_manager_users_fk; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.delivery_receipts
    ADD CONSTRAINT receipts_manager_users_fk FOREIGN KEY (manager_user_id) REFERENCES public.users(id);


--
-- Name: delivery_receipts receipts_customer_users_fk; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.delivery_receipts
    ADD CONSTRAINT receipts_customer_users_fk FOREIGN KEY (customer_user_id) REFERENCES public.users(id);


--
-- Name: directions direction_receiver_city_fk; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.directions
    ADD CONSTRAINT direction_receiver_city_fk FOREIGN KEY (receiver_city_id) REFERENCES public.cities(id);


--
-- Name: users users_address_fk; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_address_fk FOREIGN KEY (address_id) REFERENCES public.addresses(id);


--
-- Name: delivery_applications applications_sender_address_fk; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.delivery_applications
    ADD CONSTRAINT applications_sender_address_fk FOREIGN KEY (sender_address_id) REFERENCES public.addresses(id);


--
-- Name: delivery_applications applications_receiver_address_fk; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.delivery_applications
    ADD CONSTRAINT applications_receiver_address_fk FOREIGN KEY (receiver_address_id) REFERENCES public.addresses(id);


--
-- Name: delivery_applications application_baggage_fk; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.delivery_applications
    ADD CONSTRAINT application_baggage_fk FOREIGN KEY (baggage_id) REFERENCES public.delivered_baggage(id);


--
-- Name: user_role user_role_user_fk; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_role
    ADD CONSTRAINT user_role_user_fk FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- PostgreSQL database dump complete
--
